
server:
  port: ${PORT:8080}

spring:
  application:
    name: Hero API
  datasource:
    url: jdbc:postgresql://localhost:5432/hero
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update